- name: print variables from inventory file
  hosts: web
  become: yes
  tasks:
    - name: print variables from inventory file
      ansible.builtin.debug:
        msg: "Hi, i am learning {{ course }}, duration is {{ duration }} and trainer is {{ trainer }}"