- name: print facts
  hosts: web
  become: yes
  tasks:
    # - name: print facts information
    #   ansible.builtin.debug:
    #     msg: "{{ ansible_facts }}"

    - name: install nginx 
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "RedHat"