- name: loops play
  hosts: web
  become: yes
  vars:
    packages:
      - {name: mysql, state: present}
      - {name: nginx, state: absent}
      - {name: httpd, state: present}
  tasks:
    - name: print names
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        - sekhar
        - chandra
        - reddy
    - name: install packages list of hashes 
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop: "{{ packages }}"
      when: item.state == "present"
