- name: create ec2 instances for expense project
  hosts: local
  connection: local
  vars:
    vpc_subnet_id: "subnet-05fee104efdf4432a"
    security_group: "sg-00373ce1002b7759e"
    instances:
      - mysql
      - backend
      - frontend
  tasks:
    - name: create ec2 instances
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        instance_type: "t3.micro"
        security_group: "{{ security_group }}"
        image_id: "ami-09c813fb71547fc4f"
      loop: "{{ instances }}"
      register: ec2_instances

    # - name: print instance information
    #   ansible.builtin.debug:
    #     msg: "{{ ec2_instances }}"

    - name: create r53 records 
      vars:
        zone_name: "devsecmlops.online"
      amazon.aws.route53:
        state: present
        zone: "{{ zone_name }}"
        record: "{{ item.item }}.{{ zone_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances.private_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_instances.results }}"

    - name: create r53 record for frontend with public ip
      vars:
        zone_name: "devsecmlops.online"
      amazon.aws.route53:
        state: present
        zone: "{{ zone_name }}"
        record: "{{ zone_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances.public_ip_address }}"
        wait: true
        overwrite: true
      loop: "{{ ec2_instances.results }}"
      when: item.item == "frontend"
    